### ISSUE TITLE
working over any range/ignoring empty cells?

### ISSUE THREAD

**Issue by alwayslearning74** [DanGolding/Linear-and-bilinear-interpolation-in-Excel#1]
Is it possible to modify this to ignore empty cells in a range?  For example, I'm trying to set up generic sections of a spreadsheet where I can paste values into it, and I'd like for that range to be 500 cells long to avoid losing/cutting off data.  However, if my data stops on row 197, I need to manually adjust my ranges to row 197, otherwise I get VALUE errors.

It may be something simple that I'm overlooking, but I'm still just in awe that such a module exists, so I'm kinda looking everywhere at once.  Thank you for this.

**Comment by DanGolding** [comment]
I don't think the function should support that. But it's easy enough to handle in Excel using the regular `=OFFSET()` function and probably `=COUNTA()`

**Comment by DanGolding** [comment]
I don't think the function should support that. But it's easy enough to handle in Excel using the regular `=OFFSET()` function and probably `=COUNTA()`
