### ISSUE TITLE
Upper right traingle of zeros

### ISSUE THREAD

**Issue by BillKantor** [DanGolding/Linear-and-bilinear-interpolation-in-Excel#2]
This bilinear interpolation is exactly what I wanted. Thanks for this work. Saved me a lot of time.

In my use, the upper-right triangle of the "surface" is all zeros. The interpolation of intermediate values can produce non-zero values on the diagonal. (I never submit a request for above the diagonal.) 

Is there a way to force this as a boundary condition? I would like all the interpolation to treat the diagonal and everything above it as a boundary set to zero.  My matrix is not square BTW. It is taller than wide.

**Comment by DanGolding** [comment]
@BillKantor sorry for the super late reply :( You could do this fairly easily in the Excel formula itself, something like `=IF((COLUMN() - COLUMN(first_column)) > (ROW() - ROW(first_row)), 0, interp2(blabla))`
