### ISSUE TITLE
Order Matters - should be made clear

### ISSUE THREAD

**Issue by Piroshki** [DanGolding/Linear-and-bilinear-interpolation-in-Excel#3]
There seems to be a big issue with the interpolation when the data is decreasing in value. See attached image for the wrong result.

![Error](https://user-images.githubusercontent.com/10838097/111336124-54e69980-864b-11eb-86b8-3c9ef2db33a3.png)

**Comment by Piroshki** [comment]
Found an error in the code. It should be: 

    fQ11 = zArr(ly, lx)
    fQ21 = zArr(uy, lx)
    fQ12 = zArr(ly, ux)
    fQ22 = zArr(uy, ux)

and now I get decent results. Not sure where this error comes from, but it looks like zArr comes in transposed?

**Comment by Piroshki** [comment]
OK - I solved the problem, but it needs to be made clear somewhere: 

- the X direction should be vertical
- the Y direction should be horizontal

I had picked a row for X values, and a column for Y values, which lead to the problem.

**Comment by DanGolding** [comment]
> OK - I solved the problem, but it needs to be made clear somewhere:
> 
> * the X direction should be vertical
> * the Y direction should be horizontal
> 
> I had picked a row for X values, and a column for Y values, which lead to the problem.

Thanks @Piroshki , I've added a note to the README
